spring.application.name=Insurance_Project
spring.datasource.url = jdbc:mysql://localhost:3306/Insurance_Project
spring.datasource.username = Spring
spring.datasource.password = Rshivansh@094
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.fail-on-empty-beans=false